### ISSUE TITLE
Dependencies : PyJWT version is too old

### ISSUE THREAD

**Issue by aureliendebord** [docusign/docusign-esign-python-client#135]
Currently this package needs PyJWT v1.7.1. This version has been released in november 2018.
This old version is no more compatible with the current version of Django Rest Framework.

How can we solve this in order to use this docusign client with an API built with Django Reste Framework?

**Comment by fmgoncalves** [comment]
We ran into the same problem. There are now many packages in pypi that dropped support for python 2 and therefore raised the dependency on PyKWT to `>=2`, which conflicts with docusign-esign-python-client .

We understand that updating PyJWT means dropping support for any python version lower than 3.5 and that may be undesirable for docusign, so ended up forking for now (https://github.com/enhancedsociety/docusign-esign-python-client).

**Comment by aureliendebord** [comment]
FYI, I made a fork with PyJWT 2.0.3 : https://github.com/agencedebord/docusign-esign-python-client
I will make a PR for that.

**Comment by sondrelg** [comment]
@dbbrahmbhatt is it possible to get docusign's stance on this issue? We currently have unrelated 5 dependencies we cannot upgrade, because this package is blocking us. 

Is this something you'll look to fix soon, or will you want to maintain support for older python versions for a little longer?

**Comment by sondrelg** [comment]
@HobbyProjects are you able to help?

**Comment by harsharahul** [comment]
Hi @sondrelg, apologies for the delayed response. We are currently collecting metrics & evaluating the support of PY2 or changing the Auth packages. Meanwhile I would suggest to fork the package by modifying the `jwt.encode` and `jwt.decode` lines in `apiClient.py`.

In the coming two releases we will look in updating this. Thank you for your patience in this.

Thanks,
Harsha

**Comment by aureliendebord** [comment]
Regarding the @harsharahul answer and considering that some forks are available, I close this issue.
