### ISSUE TITLE
Development and build dependencies are listed as install requirements of this project

### ISSUE THREAD

**Issue by spenserblack** [docusign/docusign-esign-python-client#160]
For example, when running `pip install docusign-esign==3.19.0`, `nose` gets installed, too. As far as I can tell, `nose` is a development dependency used for testing, and is an unnecessary dependency for usage of this package. It seems like this is adding packages to user's environments that don't need to be installed.

**Comment by garg-mudit** [comment]
Hi @spenserblack ,
Please check [5.0.0rc1](https://github.com/docusign/docusign-esign-python-client/releases/tag/v5.0.0rc1) release.

The REQUIRES array has been updated along with this release.

Hopefully that addresses your issue.

Thank You.

**Comment by spenserblack** [comment]
Looks good! I gave `nose` as an example, but I don't know if `setuptools` should be listed as a dependency for end users, either.

**Comment by InbarGazit** [comment]
@spenserblack can this issue be closed?
