### ISSUE TITLE
in accounts api - update_brand_resources_by_content_type not working

### ISSUE THREAD

**Issue by adirn15** [docusign/docusign-esign-python-client#52]
the method receives account id, brand id, and resource content type but there is not option to add the file itself. 

according to the REST api documentation:

> AccountBrands: updateResource
> This method updates a branding resource file.
> 
> You pass in the new version of the resource file in the Content-Disposition header. Example:
> 
> Content-Disposition: form-data; name="file"; filename="DocuSign_SigningResource_4328673.xml"

but in the SDK there is no option to update the header params

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. The API docs reference: [AccountBrands::updateResource](https://developers.docusign.com/esign-rest-api/reference/Accounts/AccountBrands/updateResource).

I have filed bug report DCM-3866
Until it is fixed, I suggest that you implement the API method manually. An example of how to do that is in example [workflow 10](https://github.com/docusign/eg-03-python-auth-code-grant/blob/master/app/eg010_send_binary_docs.py)

**Comment by adirn15** [comment]
anything new on this issue? is a bugfix soon to be released?

**Comment by HobbyProjects** [comment]
This issue has already been fixed and is in master.
